# Generated by Django 4.2.10 on 2024-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='original_audio',
            field=models.FileField(blank=True, null=True, upload_to='original_audios/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='original_videos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='transcription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='translated_audio',
            field=models.FileField(blank=True, null=True, upload_to='translated_audios/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='voice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
