# Generated by Django 4.2.10 on 2024-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_alter_job_original_audio_alter_job_original_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='target_language',
            field=models.CharField(blank=True, choices=[('afrikaans', 'Afrikaans'), ('albanian', 'Albanian'), ('amharic', 'Amharic'), ('arabic', 'Arabic'), ('armenian', 'Armenian'), ('azerbaijani', 'Azerbaijani'), ('bashkir', 'Bashkir'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnian', 'Bosnian'), ('breton', 'Breton'), ('bulgarian', 'Bulgarian'), ('burmese', 'Burmese'), ('catalan', 'Catalan'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('english', 'English'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('flemish', 'Flemish'), ('french', 'French'), ('galician', 'Galician'), ('georgian', 'Georgian'), ('german', 'German'), ('greek', 'Greek'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hausa', 'Hausa'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('korean', 'Korean'), ('lao', 'Lao'), ('latvian', 'Latvian'), ('lingala', 'Lingala'), ('lithuanian', 'Lithuanian'), ('luxembourgish', 'Luxembourgish'), ('macedonian', 'Macedonian'), ('malagasy', 'Malagasy'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('marathi', 'Marathi'), ('moldavian', 'Moldavian'), ('moldovan', 'Moldovan'), ('mongolian', 'Mongolian'), ('nepali', 'Nepali'), ('norwegian', 'Norwegian'), ('occitan', 'Occitan'), ('panjabi', 'Panjabi'), ('pashto', 'Pashto'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('pushto', 'Pushto'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('sindhi', 'Sindhi'), ('sinhala', 'Sinhala'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sundanese', 'Sundanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tamil', 'Tamil'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('uzbek', 'Uzbek'), ('valencian', 'Valencian'), ('vietnamese', 'Vietnamese'), ('welsh', 'Welsh'), ('yiddish', 'Yiddish'), ('yoruba', 'Yoruba')], max_length=50, null=True),
        ),
    ]
